# This template patches the Keycloak ingress hostname to use the global domain
{{- $routingMode := .Values.global.ingress.routingMode | default "subdomain" }}
{{- $pathPrefix := .Values.global.ingress.paths.keycloak | default "/keycloak" }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-keycloak
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- if eq $routingMode "path" }}
    alb.ingress.kubernetes.io/group.name: mcp-gateway-stack
    alb.ingress.kubernetes.io/group.order: '30'
    {{- end }}
    {{- toYaml .Values.global.ingress.annotations | nindent 4 }}
spec:
  ingressClassName: {{ .Values.global.ingress.className }}
  rules:
    {{- if eq $routingMode "path" }}
    - host: {{ .Values.global.domain }}
      http:
        paths:
          - path: {{ $pathPrefix }}
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-keycloak-headless
                port:
                  number: 8080
    {{- else }}
    - host: keycloak.{{ .Values.global.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-keycloak-headless
                port:
                  number: 8080
    {{- end }}
